#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  4 09:42:35 2022

@author: destihuswaeni
"""

#Contoh 1 - Type Data Integer
print (12345678+1)

print(1234*5)

#Contoh 2 - Type Data
print(10)
print(type(10))

#Contoh 3 - Bilangan Floating-Point (Decimal/Pecahan)
print(4.2)
print(type(4.2))
print(4.)
print(.2)
print(.4e7)
print(4.2e-4)

#Contoh 4 - Strings (Karakter/Huruf singkatannya str)
print('Hacktiv8')
print(type('Hactiv8'))

#Contoh 5 - Boolean (True or False)
print(type(True))

#Contoh 6 - Variable Assignment (variable pengganti)
n=300
print(n)

#Latihan 6
a=10
t=20
L=1/2*a*t
print(L)

a=b=c=300
print(a,b,c)

#Contoh 7 - Variable Types in Phyton
var = 23.5
print (var)

var = "now I'm a string"
print(var)


#Contoh 8 = Variable Name
name = 'Hactiv8' #Karakter harus menggunakan kutip
age = 54
has_laptop = True
print (name,age,has_laptop)

age = 1
Age = 2
aGe = 3
AGE = 4
AGE = 10
a_g_e = 5
_age = 6
age_ = 7
_age_ = 8
print(age,Age,aGe,AGE,a_g_e,_age,age_,_age_)
#Untuk string case sensitif dan jika double maka nilai akan menggantikan nilai yang sebelumnya)

#Contoh 9 = Variable Expression (+,-,*,/)
a = 10
b = 20
print(a + b)

a = 10
b = 20
print(a+b-5)

#Contoh 10 : Arithmatic Operator
a = 4
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)

#Contoh 10 = Comparison Operators
a = 10
b = 20
print(a == b)

print(a != b) #Tidak sama dengan

print(a <= b)

print(a >= b)


a = 30
b = 30
print(a == b)

print(a <= b)

print(a >= b)

#Contoh 11 - String Manipulation
# + Operators
s = 'foo'
t = 'bar'
u = 'baz'
print(s + t)
print(s + t + u)
print('Hacktiv8 ' + 'PTP')

s = 'foo.'
print (s * 4)



